#!/bin/sh
set -eu

CONFIG_DIR="${MARKET_STACK_CONFIG_DIR:-/data/config}"
CONFIG_FILE="${MARKET_STACK_CONFIG_FILE:-$CONFIG_DIR/ananta-market-stack.env}"
DATA_DIR="${MARKET_STACK_DATA_DIR:-/data}"
REDIS_DATA_DIR="${MARKET_STACK_REDIS_DATA_DIR:-$DATA_DIR/redis}"
BACKEND_HOST="${MARKET_STACK_BACKEND_HOST:-127.0.0.1}"
BACKEND_PORT="${MARKET_STACK_BACKEND_PORT:-8000}"
PUBLIC_PORT="${PORT:-3000}"
FRONTEND_PORT="${MARKET_STACK_FRONTEND_PORT:-3001}"

log() {
  printf '%s\n' "$*"
}

random_fernet_key() {
  python - <<'PY'
import base64
import os
print(base64.urlsafe_b64encode(os.urandom(32)).decode("ascii"))
PY
}

random_token() {
  python - <<'PY'
import secrets
print(secrets.token_urlsafe(32))
PY
}

env_value() {
  key="$1"
  current="$(printenv "$key" 2>/dev/null || true)"
  if [ -n "$current" ]; then
    printf '%s' "$current"
    return
  fi
  if [ -f "$CONFIG_FILE" ]; then
    awk -F= -v key="$key" '$1 == key {sub(/^[^=]*=/, ""); print; exit}' "$CONFIG_FILE"
  fi
}

load_generated_env() {
  if [ ! -f "$CONFIG_FILE" ]; then
    return
  fi

  while IFS= read -r line || [ -n "$line" ]; do
    case "$line" in
      ""|\#*) continue ;;
    esac
    key="${line%%=*}"
    value="${line#*=}"
    current="$(printenv "$key" 2>/dev/null || true)"
    if [ -z "$current" ]; then
      export "$key=$value"
    fi
  done < "$CONFIG_FILE"
}

write_generated_env() {
  mkdir -p "$CONFIG_DIR"
  existing_credential="$(env_value CREDENTIAL_ENCRYPTION_KEY)"
  existing_auth="$(env_value BETTER_AUTH_SECRET)"
  existing_redis="$(env_value REDIS_PASSWORD)"

  credential_key="${existing_credential:-$(random_fernet_key)}"
  auth_secret="${existing_auth:-$(random_token)}"
  redis_password="$existing_redis"
  if [ -z "$redis_password" ] && [ -z "${REDIS_URL:-}" ]; then
    redis_password="$(random_token)"
  fi

  tmp_file="${CONFIG_FILE}.tmp"
  {
    printf '%s\n' "# Generated by the Ananta Market Stack container."
    printf '%s\n' "# Back up this file with /data/app.db. Do not commit it."
    printf 'CREDENTIAL_ENCRYPTION_KEY=%s\n' "$credential_key"
    printf 'BETTER_AUTH_SECRET=%s\n' "$auth_secret"
    if [ -n "$redis_password" ]; then
      printf 'REDIS_PASSWORD=%s\n' "$redis_password"
    fi
  } > "$tmp_file"
  chmod 600 "$tmp_file"
  mv "$tmp_file" "$CONFIG_FILE"
}

wait_for_backend() {
  i=0
  while [ "$i" -lt 60 ]; do
    if python - <<PY >/dev/null 2>&1
import urllib.request
urllib.request.urlopen("http://$BACKEND_HOST:$BACKEND_PORT/ready", timeout=2).read()
PY
    then
      return 0
    fi
    i=$((i + 1))
    sleep 1
  done
  log "Backend did not become healthy in time."
  return 1
}

wait_for_frontend() {
  i=0
  while [ "$i" -lt 60 ]; do
    if python - <<PY >/dev/null 2>&1
import urllib.request
urllib.request.urlopen("http://127.0.0.1:$FRONTEND_PORT/api/health", timeout=2).read()
PY
    then
      return 0
    fi
    i=$((i + 1))
    sleep 1
  done
  log "Frontend did not become healthy in time."
  return 1
}

runtime_is_ready() {
  python - <<PY
import sys
import urllib.request

for url in (
    "http://$BACKEND_HOST:$BACKEND_PORT/ready",
    "http://127.0.0.1:$FRONTEND_PORT/api/health",
    "http://127.0.0.1:$PUBLIC_PORT/api/health",
):
    try:
        urllib.request.urlopen(url, timeout=3).read(1)
    except Exception as exc:
        print(f"Runtime readiness probe failed for {url}: {exc}", file=sys.stderr)
        raise SystemExit(1)
PY
}

write_nginx_config() {
  cat > /etc/nginx/nginx.conf <<EOF
events {}

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  sendfile on;

  map \$http_upgrade \$connection_upgrade {
    default upgrade;
    '' close;
  }

  server {
    listen $PUBLIC_PORT;
    server_name _;

    client_max_body_size 25m;

    location /api/v1/ {
      proxy_pass http://$BACKEND_HOST:$BACKEND_PORT/api/v1/;
      proxy_http_version 1.1;
      proxy_set_header Host \$http_host;
      proxy_set_header X-Forwarded-Host \$http_host;
      proxy_set_header X-Real-IP \$remote_addr;
      proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto \$scheme;
      proxy_set_header Upgrade \$http_upgrade;
      proxy_set_header Connection \$connection_upgrade;
      proxy_read_timeout 3600s;
      proxy_send_timeout 3600s;
      proxy_buffering off;
    }

    location / {
      proxy_pass http://127.0.0.1:$FRONTEND_PORT;
      proxy_http_version 1.1;
      proxy_set_header Host \$http_host;
      proxy_set_header X-Forwarded-Host \$http_host;
      proxy_set_header X-Real-IP \$remote_addr;
      proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto \$scheme;
      proxy_set_header Upgrade \$http_upgrade;
      proxy_set_header Connection \$connection_upgrade;
      proxy_read_timeout 3600s;
      proxy_send_timeout 3600s;
    }
  }
}
EOF
}

signal_child() {
  pid="${1:-}"
  if [ -n "$pid" ] && kill -0 "$pid" 2>/dev/null; then
    kill "$pid" 2>/dev/null || true
  fi
}

wait_for_child_exit() {
  pid="${1:-}"
  max_seconds="${2:-5}"
  elapsed=0
  while [ -n "$pid" ] && kill -0 "$pid" 2>/dev/null && [ "$elapsed" -lt "$max_seconds" ]; do
    sleep 1
    elapsed=$((elapsed + 1))
  done
  if [ -n "$pid" ] && kill -0 "$pid" 2>/dev/null; then
    kill -KILL "$pid" 2>/dev/null || true
  fi
  if [ -n "$pid" ]; then
    wait "$pid" 2>/dev/null || true
  fi
}

stop_children() {
  # Stop accepting browser traffic first, then let FastAPI close broker
  # websockets while Redis is still available. Redis is always stopped last.
  signal_child "${NGINX_PID:-}"
  signal_child "${FRONTEND_PID:-}"
  signal_child "${BACKEND_PID:-}"
  wait_for_child_exit "${BACKEND_PID:-}" 7
  wait_for_child_exit "${FRONTEND_PID:-}" 3
  wait_for_child_exit "${NGINX_PID:-}" 3
  signal_child "${REDIS_PID:-}"
  wait_for_child_exit "${REDIS_PID:-}" 5
}

trap 'stop_children; wait || true; exit 0' INT TERM

mkdir -p "$DATA_DIR" "$CONFIG_DIR" "$REDIS_DATA_DIR" "$DATA_DIR/logs"
write_generated_env
load_generated_env

export DATABASE_URL="${DATABASE_URL:-sqlite:///$DATA_DIR/app.db}"
export AUTH_DATABASE_PATH="${AUTH_DATABASE_PATH:-$DATA_DIR/app.db}"
export ALLOW_INSECURE_DEV_CREDENTIALS="${ALLOW_INSECURE_DEV_CREDENTIALS:-false}"
export MARKET_STACK_API_INTERNAL_URL="${MARKET_STACK_API_INTERNAL_URL:-http://$BACKEND_HOST:$BACKEND_PORT/api/v1}"
export NEXT_PUBLIC_API_BASE_URL="${NEXT_PUBLIC_API_BASE_URL:-${MARKET_STACK_PUBLIC_API_BASE_URL:-/api/v1}}"
export MARKET_STACK_PUBLIC_API_BASE_URL="${MARKET_STACK_PUBLIC_API_BASE_URL:-$NEXT_PUBLIC_API_BASE_URL}"
export NEXT_PUBLIC_APP_URL="${NEXT_PUBLIC_APP_URL:-${MARKET_STACK_PUBLIC_APP_URL:-http://localhost:$PUBLIC_PORT}}"
export MARKET_STACK_PUBLIC_APP_URL="${MARKET_STACK_PUBLIC_APP_URL:-$NEXT_PUBLIC_APP_URL}"
export BETTER_AUTH_URL="${BETTER_AUTH_URL:-$MARKET_STACK_PUBLIC_APP_URL}"
export BETTER_AUTH_TRUSTED_ORIGINS="${BETTER_AUTH_TRUSTED_ORIGINS:-$MARKET_STACK_PUBLIC_APP_URL,http://localhost:$PUBLIC_PORT,http://127.0.0.1:$PUBLIC_PORT}"
export APP_PUBLIC_BASE_URL="${APP_PUBLIC_BASE_URL:-$MARKET_STACK_PUBLIC_APP_URL}"

if [ -z "${REDIS_URL:-}" ]; then
  export REDIS_HOST="${REDIS_HOST:-127.0.0.1}"
  export REDIS_PORT="${REDIS_PORT:-6379}"
  export REDIS_DB="${REDIS_DB:-0}"
  log "Starting bundled Redis on $REDIS_HOST:$REDIS_PORT"
  redis-server \
    --appendonly yes \
    --appendfsync everysec \
    --auto-aof-rewrite-percentage 100 \
    --auto-aof-rewrite-min-size 128mb \
    --save "" \
    --dir "$REDIS_DATA_DIR" \
    --bind "$REDIS_HOST" \
    --port "$REDIS_PORT" \
    --requirepass "$REDIS_PASSWORD" &
  REDIS_PID="$!"
else
  log "Using external Redis from REDIS_URL."
fi

cd /app/backend
python -m uvicorn app.main:app --host "$BACKEND_HOST" --port "$BACKEND_PORT" &
BACKEND_PID="$!"

wait_for_backend

cd /app/frontend
HOSTNAME=0.0.0.0 PORT="$FRONTEND_PORT" node server.js &
FRONTEND_PID="$!"

wait_for_frontend

write_nginx_config
nginx -g "daemon off;" &
NGINX_PID="$!"

health_check_ticks=0
health_check_failures=0
while :; do
  if ! kill -0 "$NGINX_PID" 2>/dev/null; then
    wait "$NGINX_PID" || exit_code="$?"
    break
  fi
  if ! kill -0 "$BACKEND_PID" 2>/dev/null; then
    wait "$BACKEND_PID" || exit_code="$?"
    break
  fi
  if ! kill -0 "$FRONTEND_PID" 2>/dev/null; then
    wait "$FRONTEND_PID" || exit_code="$?"
    break
  fi
  if [ -n "${REDIS_PID:-}" ] && ! kill -0 "$REDIS_PID" 2>/dev/null; then
    wait "$REDIS_PID" || exit_code="$?"
    break
  fi
  health_check_ticks=$((health_check_ticks + 1))
  if [ "$health_check_ticks" -ge 5 ]; then
    health_check_ticks=0
    if runtime_is_ready; then
      health_check_failures=0
    else
      health_check_failures=$((health_check_failures + 1))
      log "Runtime readiness check failed ($health_check_failures/3)."
      if [ "$health_check_failures" -ge 3 ]; then
        log "Runtime remained unhealthy; exiting so the container restart policy can recover it."
        exit_code=1
        break
      fi
    fi
  fi
  sleep 1
done

stop_children
wait || true
exit "${exit_code:-1}"
