from __future__ import annotations

import base64
import os
import secrets
from pathlib import Path


CONFIG_PATH = Path("/config/market-stack.env")


def _fernet_key() -> str:
    return base64.urlsafe_b64encode(os.urandom(32)).decode("ascii")


def _token() -> str:
    return secrets.token_urlsafe(32)


def _read_existing() -> dict[str, str]:
    values: dict[str, str] = {}
    if not CONFIG_PATH.exists():
        return values
    for raw_line in CONFIG_PATH.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key] = value
    return values


def main() -> None:
    values = _read_existing()
    values["CREDENTIAL_ENCRYPTION_KEY"] = (
        os.environ.get("CREDENTIAL_ENCRYPTION_KEY")
        or values.get("CREDENTIAL_ENCRYPTION_KEY")
        or _fernet_key()
    )
    values["BETTER_AUTH_SECRET"] = (
        os.environ.get("BETTER_AUTH_SECRET")
        or values.get("BETTER_AUTH_SECRET")
        or _token()
    )
    values["REDIS_PASSWORD"] = (
        os.environ.get("REDIS_PASSWORD")
        or values.get("REDIS_PASSWORD")
        or _token()
    )

    CONFIG_PATH.parent.mkdir(parents=True, exist_ok=True)
    CONFIG_PATH.write_text(
        "\n".join(
            [
                "# Generated by the Market-Stack Docker bootstrap service.",
                "# Back up this file with the app data volume.",
                f"CREDENTIAL_ENCRYPTION_KEY={values['CREDENTIAL_ENCRYPTION_KEY']}",
                f"BETTER_AUTH_SECRET={values['BETTER_AUTH_SECRET']}",
                f"REDIS_PASSWORD={values['REDIS_PASSWORD']}",
                "",
            ]
        ),
        encoding="utf-8",
    )
    CONFIG_PATH.chmod(0o644)


if __name__ == "__main__":
    main()
